---
volumes:
  mysql-data:
    driver: local
  mysql-logs:
    driver: local
  mysql-lib:
    driver: local
services:
  mysql:
    hostname: mysql
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "dev"
      MYSQL_ROOT_HOST: "%"
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/data/mysql
      - mysql-logs:/var/logs/mysql
      - mysql-lib:/var/lib/mysql
